apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: flask-app  # placeholder to match the image name in kustomization.yaml
        ports:
        - containerPort: 4000
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-api-key-secret
                key: OPENAI_API_KEY
          - name: PINECONE_KEY
            valueFrom:
              secretKeyRef:
                name: pinecone-key-secret
                key: PINECONE_KEY
          - name: PINECONE_INDEX_NAME
            valueFrom:
              secretKeyRef:
                name: pinecone-index-name-secret
                key: PINECONE_INDEX_NAME
