apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
images:
  - name: flask-app
    newName: us-central1-docker.pkg.dev/${PROJECT_ID}/supply-chain-services/rag-image
    newTag: latest
