apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
images:
  - name: us-central1-docker.pkg.dev/PROJECT_ID/samples/rag-image
    newName: us-central1-docker.pkg.dev/PROJECT_ID/samples/rag-image
    newTag: latest
